
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/jquery/select2
	@mkdir  ../../sea-modules/jquery/select2
	@mkdir  ../../sea-modules/jquery/select2/3.5.2
	@cp     dist/*.* ../../sea-modules/jquery/select2/3.5.2
	@rm -rf dist
	@echo
	@echo   " deploy to sea-modules/jquery/select2/3.5.2"
	@echo
