
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/jquery/lazyload
	@mkdir  ../../sea-modules/jquery/lazyload
	@mkdir  ../../sea-modules/jquery/lazyload/1.9.3
	@cp     dist/*.* ../../sea-modules/jquery/lazyload/1.9.3
	@rm -rf dist
	@echo
	@echo   " deploy to sea-modules/jquery/lazyload/1.9.3"
	@echo
