
build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/jquery/simple-pagination
	@mkdir  ../../sea-modules/jquery/simple-pagination
	@mkdir  ../../sea-modules/jquery/simple-pagination/1.6.0
	@cp     dist/*.* ../../sea-modules/jquery/simple-pagination/1.6.0
	@rm -rf dist
	@echo
	@echo   " deploy to sea-modules/jquery/simple-pagination/1.6.0"
	@echo
